import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} pb-8 bg-blue-50 text-slate-900 antialiased`}
      >
        <div className="flex flex-col justify-between w-full h-full min-h-screen">
          {children}
        </div>
      </body>
    </html>
  )
}
